server:
  port: 7777

spring:
  datasource:
    #로컬 유저의 경우 아래와 같이 사용합니다.
    url: jdbc:mysql://localhost:3306/spring_html_db?serverTimezone=UTC&useSSL=false
    #도커 유저의 경우엔 좀 더 설정이 필요합니다.
    #url: jdbc:mysql://192.168.99.100:3307/spring_html_db?serverTimezone=UTC&useSSL=false
    username: khweb
    password: khdkdlxl@123
    driver-class-name: com.mysql.cj.jdbc.Driver

