server:
  port: 7777

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: phh
    password: phh
    driver-class-name: oracle.jdbc.OracleDriver


mybatis:
  mapper-locations: mybatis/**/*-mapper.xml
  type-aliases-package: com.siblings.shoppingmall.entity
  configuration:
    map-underscore-to-camel-case: true
