CREATE TABLE BOARD
(
    BOARD_NO NUMBER PRIMARY KEY,
	BOARD_TITLE VARCHAR2(100 BYTE),
	BOARD_CONTENT VARCHAR2(4000 BYTE),
	BOARD_WRITER VARCHAR2(2000 BYTE)
);
CREATE SEQUENCE BOARD_SEQ;

INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (1,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (2,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (3,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (4,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (5,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (6,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (7,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (8,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (9,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (10,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (11,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (12,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (13,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (14,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (15,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (16,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (17,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (18,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (19,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (20,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (21,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (22,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (23,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (24,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (25,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (26,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (27,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (28,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (29,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (30,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (31,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (32,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (33,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (43,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (44,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (45,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (46,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (47,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (48,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (49,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (50,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (51,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (52,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (53,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (54,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (55,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (56,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (57,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (58,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (59,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (60,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (61,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (62,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (63,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (64,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (65,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (66,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (67,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (68,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (69,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (70,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (71,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (72,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (73,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (74,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (75,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (76,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (77,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (78,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (79,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (80,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (81,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (82,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (83,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (84,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (85,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (86,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (87,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (88,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (89,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (90,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (91,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (92,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (93,'test5','testContent5','a5');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (94,'test','testContent','a');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (95,'test2','testContent2','a2');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (96,'test3','testContent3','a3');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (97,'test4','testContent4','a4');
INSERT INTO BOARD
	(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER)
VALUES (98,'test5','testContent5','a5');
